owner: "52316556"
team: "13347347"
lastUpdatedBy: "52316556"
lastRevision: 1786493008000
name: Dev Environment
color: 0
values:
  - key: apiKey
    enabled: true
    secret: true
    source:
      provider: postman
      postman:
        type: cloud
        secretId: bc4e14d9-0011-4637-b916-b3a059580df3
        vaultId: b8895514-4510-4423-bf28-91f5f1c2b083
  - key: baseUrl
    value: http://localhost:4500
    enabled: true
  - key: airportCode
    value: ATL
    enabled: true
createdAt: 2026-03-26T00:14:18.000Z
updatedAt: 2026-08-12T00:03:28.000Z
