name: Production Environment Copy
values:
  - key: apiKey
    secret: true
    source:
      provider: postman
      postman:
        type: cloud
        secretId: bc4e14d9-0011-4637-b916-b3a059580df3
        vaultId: b8895514-4510-4423-bf28-91f5f1c2b083
  - key: baseUrl
    value: 'https://education.postmanlabs.com/v1/weather'
  - key: airportCode
    value: ATL
color: 0
